/**
* @Authors Abhijit Kane
* Main validator file
*/
 
var program = require('commander'),
	fs      = require('fs'),
	JSV = require("JSV").JSV;

var global_schema = require('./json-schemas/globals.schema.json');
var env_schema = require('./json-schemas/environment.schema.json');
var collection_schema = require('./json-schemas/collection.schema.json');


function loadJSONfile (filename, encoding) {
	if(!fs.existsSync(filename)) {
		printError("File " + filename+" could not be found\n");
	}
	var contents=null;
	try {
		if (typeof (encoding) == 'undefined') encoding = 'utf8';
		var contents = fs.readFileSync(filename, encoding);
	} catch (err) {
		process.stdout.write(err);
		process.exit(-1);
	}

	try {
		return JSON.parse(contents);
	} catch(err) {
		process.stdout.write("Invalid json\n");
		process.exit(-1);
	}
}

function parseArguments() {
	program
	  .version('0.0.0')
	  .usage('[option]')
	  .option('-c, --collection [file]', 'Validate the input file against the collection schema', null)
      .option('-e, --environment [file]', 'Validate the input file against the environment schema', null)
      .option('-g, --globals [file]', 'Validate the input file against the globals schema', null);

	program.on('--help', function() {
	  console.log('  Validates files generated by Postman');
	  console.log('');
	  console.log('  Examples:');
	  console.log('');
	  console.log('    validator -c POSTMAN_COLLECTION.json');
	  console.log('    validator -e POSTMAN_ENVIRONMENT.json');
      console.log('    validator -g POSTMAN_GLOBALS.json');
	  console.log('');
	});

	program.parse(process.argv);

	if(program.collection) {
		if(program.environment || program.globals) {
			onlyOneValidator();
		}

		return validate(collection_schema,program.collection);
	}
	else if(program.environment) {
		if(program.globals) {
			onlyOneValidator();
		}
		return validate(env_schema,program.environment);
	}
	else if(program.globals) {
		return validate(global_schema,program.globals);
	}
	else {
		printError("At least one option must be specified. Use --help to see the list of options\n");
	}
}

function validate(schema, input) {
	input = loadJSONfile(input);
	var env = JSV.createEnvironment();
	var report = env.validate(input, schema);
	if(report.errors.length) {
		process.stdout.write("Validation failed\n");
		return report.errors;
	}

}

function onlyOneValidator() {
	printError("Only one type of validation can be used at one time");
}

function printError(str) {
	process.stdout.write(str);
	process.exit(1);
}

function main() {
	return parseArguments();
}

main();
